version: '3.9'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Express
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'yourStrong(!)Password' -Q 'SELECT 1' -No -C"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db_init
    volumes:
      - ./createDbSqlServer.sql:/createDbSqlServer.sql
    environment:
      - ACCEPT_EULA=Y
    networks:
      - backend
    depends_on:
      sqlserver:
        condition: service_healthy
    command: >
      /bin/bash -c "
        /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P 'yourStrong(!)Password' -i /createDbSqlServer.sql -No -C &&
        echo 'BD inicializada correctamente.'
      "
    restart: "no"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet_api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=MambaTeam;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      - JWT__ValidAudience=https://localhost:7000
      - JWT__ValidIssuer=https://localhost:7278
      - JWT__SecretKey=MyPass@word2MyPass@word2MyPass@word2
    depends_on:
      db-init:
        condition: service_completed_successfully
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:

volumes:
  sqlserver_data: