version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=MambaTeam
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourStrong(!)Password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./createDb.sql:/docker-entrypoint-initdb.d/createDb.sql  # Se ejecuta automáticamente al crear el contenedor
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet_api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=MambaTeam;Username=postgres;Password=yourStrong(!)Password
      - JWT__ValidAudience=https://localhost:7000
      - JWT__ValidIssuer=https://localhost:7278
      - JWT__SecretKey=MyPass@word2MyPass@word2MyPass@word2
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:

volumes:
  postgres_data: